### ISSUE TITLE
FileSystemException: Cannot open file, path = 'GeigerApi.miCyberrangePlugin.state' (OS Error: Read-only file system, errno = 30)

### ISSUE THREAD

**Issue by luongnv89** [cyber-geiger/toolbox-communicationApi#4]
**Describe the bug**
Cannot initialize the Geiger API

**Environmental information**
- Bug on: Android Device (Android 8.1.0)/ Android Emulator (Android 11 - sdk 30)
- dependencies (pubspec.yaml)
```yaml
dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  sqlite3_flutter_libs: ^0.5.0
  sqflite: ^2.0.0+4
  package_info_plus: ^1.3.0
  # geiger_localstorage: ^0.5.6
  geiger_api: ^0.5.3
  permission_handler: ^8.3.0
```

**To Reproduce**
Try to get geiger api while starting the application
```dart
try {
    geigerApi = await getGeigerApi('<unspecified>', 'miCyberrangePlugin');
  } catch (e) {
    log('Failed to get the GeigerAPI');
    log(e.toString());
  }
```

Full source code can be found here (simple & short): https://github.com/luongnv89/geiger_api_test/blob/geiger_api/lib/main.dart

**Expected behavior**
The application can start, all the permissions have been granted, but failed to create the Geiger API

**Screenshots**
If applicable, add screenshots to help explain your problem (please: no code in screenshots).
```bash
I/flutter ( 5140): storagePermissionStatus: PermissionStatus.granted
I/flutter ( 5140): manageExternalStoragePermissionStatus: PermissionStatus.granted
E/flutter ( 5140): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = 'GeigerApi.miCyberrangePlugin.state' (OS Error: Read-only file system, errno = 30)
E/flutter ( 5140): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 5140): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 5140): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 5140): <asynchronous suspension>
E/flutter ( 5140):
[log] Start building the application
```

**Additional context**
- add `permission_handler` package to handle the permission
- All permissions have been granted (as the log shows)

**Possible cause of the problem**
- when reading/writing the plugin state, the path of the file `GeigerApi.miCyberrangePlugin.state` is not in a good location (means not in the sandbox of Android application).
- maybe we can add `path_provider` to have the correct path of the file
```dart
Directory appDocDirectory = await getApplicationDocumentsDirectory();

new Directory(appDocDirectory.path+'/'+'dir').create(recursive: true)
// The created directory is returned as a Future.
    .then((Directory directory) {
  print('Path of New Dir: '+directory.path);
});
```

**Comment by luongnv89** [comment]
**Update**
Adding `path_provider` have resolved the problem with the path. 

```dart
Future<String> getPluginPath(String pluginId) async {
  Directory dirPath = await getApplicationDocumentsDirectory();
  return '${dirPath.path}/$pluginId';
}

Future<void> initGeigerAPI() async {
  try {
    String pluginIDFile = await getPluginPath('miCyberrangePlugin');
    log('PluginID file path $pluginIDFile');
    geigerApi = await getGeigerApi('<unspecified>', pluginIDFile);
  } catch (e) {
    log('Failed to get the GeigerAPI');
    log(e.toString());
  }
}
```

But then it leads to another problem

```sh
I/flutter ( 5584): storagePermissionStatus: PermissionStatus.granted
I/flutter ( 5584): manageExternalStoragePermissionStatus: PermissionStatus.granted
[log] PluginID file path /data/user/0/com.example.toolbox_api_test/app_flutter/miCyberrangePlugin
E/flutter ( 5584): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = 'GeigerApi./data/user/0/com.example.toolbox_api_test/app_flutter/miCyberrangePlugin.state' (OS Error: No such file or directory, errno = 2)
E/flutter ( 5584): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 5584): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 5584): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 5584): <asynchronous suspension>
```

-> At the beginning the plugin state file does not exist

**Comment by luongnv89** [comment]
I have tried to simplify the test by using the Master Plugin API,
```dart
flushGeigerApiCache();
geigerApi = await getGeigerApi('', GeigerApi.masterId, Declaration.doNotShareData);
```

it threw the same system error
```bash
E/flutter ( 7555): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = 'GeigerApi.__MASTERPLUGIN__.state' (OS Error: Read-only file system, errno = 30)
E/flutter ( 7555): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 7555): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 7555): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 7555): <asynchronous suspension>
```

I think we are still dealing with the different structure (directory path) of the application in PC environment vs mobile environment.

**Comment by martingwerder** [comment]
Published a version on the development branch (not on pub.dev). If someone could confirm that the issue is gone it would be great.

**Comment by luongnv89** [comment]
I can confirm that the new update has fixed the problem relates to the `read-only file system`. This issue can be closed. Bravo & thank to @martingwerder

**Comment by martingwerder** [comment]
Thanks for confirming. I will publish it as 0.5.4 on pub.dev
